import type { GeneratedFunnelAssets } from "@/types/generation";

function h1(t: string) { return `# ${t}\n`; }
function h2(t: string) { return `\n## ${t}\n`; }
function h3(t: string) { return `\n### ${t}\n`; }
function hr()          { return `\n---\n`; }
function p(t: string)  { return `${t}\n`; }
function li(t: string) { return `- ${t}`; }
function bold(t: string) { return `**${t}**`; }

export function generateMarkdown(assets: GeneratedFunnelAssets, projectName: string): string {
  const lines: string[] = [];

  lines.push(h1(`${projectName} — Funnel Copy`));
  lines.push(p(`*Generated by FitPro Launch · ${new Date().toLocaleDateString("en-GB", { day: "numeric", month: "long", year: "numeric" })}*`));
  lines.push(hr());

  // ── Offer Summary ────────────────────────────────────────────────────────────
  const os = assets.offerSummary;
  if (os) {
    lines.push(h2("Offer Summary"));
    lines.push(h3("Challenge Concept"));   lines.push(p(os.challengeConcept));
    lines.push(h3("Target Audience"));    lines.push(p(os.targetAudienceSummary));
    lines.push(h3("Offer Positioning"));  lines.push(p(os.offerPositioning));
    lines.push(h3("Core Promise"));       lines.push(p(os.corePromise));
    lines.push(hr());
  }

  // ── Landing Page ──────────────────────────────────────────────────────────────
  const lp = assets.landingPage;
  if (lp) {
    lines.push(h2("Landing Page Copy"));
    lines.push(h3("Headline Options"));
    lp.headlineOptions.forEach((h) => lines.push(li(h)));
    lines.push("");
    lines.push(h3("Subheadline")); lines.push(p(lp.subheadline));
    lines.push(h3("Bullet Points"));
    lp.bulletPoints.forEach((b) => lines.push(li(b)));
    lines.push("");
    lines.push(h3("CTA Text"));  lines.push(p(lp.ctaText));
    if (lp.faqItems?.length) {
      lines.push(h3("FAQ"));
      lp.faqItems.forEach((f) => {
        lines.push(`\n${bold(f.question)}\n${f.answer}`);
      });
    }
    lines.push(hr());
  }

  // ── Application Landing Page ─────────────────────────────────────────────────
  const al = assets.applicationLandingPage;
  if (al) {
    lines.push(h2("Registration Page Copy"));
    lines.push(h3("Hero")); lines.push(p(al.valuePropHeadline)); lines.push(p(al.valuePropSubheadline));
    lines.push(h3("CTA")); lines.push(p(al.heroCtaText)); lines.push(p(al.heroCtaSubtext));
    if (al.benefitBlocks?.length) {
      lines.push(h3("Benefit Blocks"));
      al.benefitBlocks.forEach((b) => lines.push(`\n${bold(b.heading)}\n${b.body}`));
    }
    if (al.whatYouGetItems?.length) {
      lines.push(h3("What You Get"));
      al.whatYouGetItems.forEach((i) => lines.push(li(i)));
      lines.push("");
    }
    if (al.shouldApply?.length) {
      lines.push(h3("Who It's For"));
      al.shouldApply.forEach((q) => lines.push(li(q)));
      lines.push("");
    }
    if (al.shouldNotApply?.length) {
      lines.push(h3("Who It's NOT For"));
      al.shouldNotApply.forEach((q) => lines.push(li(q)));
      lines.push("");
    }
    if (al.textTestimonials?.length) {
      lines.push(h3("Testimonials"));
      al.textTestimonials.forEach((t) => {
        lines.push(`\n> "${t.quote}"\n> — ${t.attribution} | ${t.result}`);
      });
    }
    if (al.faqItems?.length) {
      lines.push(h3("FAQ"));
      al.faqItems.forEach((f) => lines.push(`\n${bold(f.question)}\n${f.answer}`));
    }
    lines.push(hr());
  }

  // ── Email Sequence ────────────────────────────────────────────────────────────
  const emails = assets.emailSequence;
  if (emails) {
    lines.push(h2("Email Sequence"));
    const emailKeys = [
      ["welcome", "Welcome"],
      ["valueDelivery", "Quick Win"],
      ["socialProof", "Social Proof"],
      ["objectionHandling", "Objection Handling"],
      ["lastChance", "Last Chance"],
      ["dayOneKickoff", "Day 1 Kickoff"],
      ["midChallenge", "Mid-Challenge"],
      ["finalStretch", "Final Stretch"],
      ["challengeComplete", "Challenge Complete"],
      ["reEngagement", "Re-Engagement"],
    ] as const;
    emailKeys.forEach(([key, label]) => {
      const e = emails[key];
      if (e) {
        lines.push(h3(`Email: ${label}`));
        lines.push(`${bold("Subject:")} ${e.subject}`);
        lines.push(`\n${e.body}`);
      }
    });
    lines.push(hr());
  }

  // ── SMS Sequence ──────────────────────────────────────────────────────────────
  const sms = assets.smsSequence;
  if (sms) {
    lines.push(h2("SMS Sequence"));
    const smsKeys = [
      ["confirmation", "Confirmation"],
      ["challengeReminder", "Challenge Reminder"],
      ["dayOneKickoff", "Day 1 Kickoff"],
      ["midChallengeMotivation", "Mid-Challenge"],
      ["noShow", "No-Show"],
      ["challengeComplete", "Challenge Complete"],
      ["reEngagement", "Re-Engagement"],
    ] as const;
    smsKeys.forEach(([key, label]) => {
      const s = (sms as Record<string, string>)[key];
      if (s) {
        lines.push(h3(`SMS: ${label}`));
        lines.push(p(s));
      }
    });
    lines.push(hr());
  }

  // ── Ad Copy ───────────────────────────────────────────────────────────────────
  const ads = assets.adCopy;
  if (ads) {
    lines.push(h2("Ad Copy"));
    if (ads.hooks?.length) {
      lines.push(h3("Hooks / Opening Lines"));
      ads.hooks.forEach((h) => lines.push(li(h)));
      lines.push("");
    }
    if (ads.primaryTexts?.length) {
      lines.push(h3("Primary Text"));
      ads.primaryTexts.forEach((t, i) => lines.push(`\n${bold(`Option ${i + 1}`)}\n${t}`));
    }
    if (ads.headlines?.length) {
      lines.push(h3("Headlines"));
      ads.headlines.forEach((h) => lines.push(li(h)));
      lines.push("");
    }
    if (ads.descriptions?.length) {
      lines.push(h3("Descriptions"));
      ads.descriptions.forEach((d) => lines.push(li(d)));
      lines.push("");
    }
    lines.push(hr());
  }

  // ── VSL Script (application) ──────────────────────────────────────────────────
  const vsl = assets.vslScript;
  if (vsl) {
    lines.push(h2("VSL Script"));
    const sections = [
      ["hook", "Hook"],
      ["problemStatement", "Problem Statement"],
      ["agitation", "Agitation"],
      ["coachStoryBridge", "Coach Story Bridge"],
      ["solutionReveal", "Solution Reveal"],
      ["programmeWalkthrough", "Programme Walkthrough"],
      ["socialProof", "Social Proof"],
      ["offerPresentation", "Offer Presentation"],
      ["objectionHandling", "Objection Handling"],
      ["callToAction", "Call to Action"],
      ["closingScarcity", "Closing / Scarcity"],
    ] as const;
    sections.forEach(([key, label]) => {
      const val = (vsl as Record<string, string>)[key];
      if (val) { lines.push(h3(label)); lines.push(p(val)); }
    });
    lines.push(hr());
  }

  // ── Campaign Naming ───────────────────────────────────────────────────────────
  const cn = assets.campaignNaming;
  if (cn) {
    lines.push(h2("Campaign Naming & UTMs"));
    lines.push(`${bold("Campaign:")} ${cn.campaignName}`);
    lines.push(`${bold("Ad Set Convention:")} ${cn.adSetNamingConvention}`);
    lines.push(`${bold("Ad Convention:")} ${cn.adNamingConvention}`);
    lines.push(`${bold("UTM:")} utm_source=${cn.utmSource}&utm_medium=${cn.utmMedium}&utm_campaign=${cn.utmCampaign}&utm_content=${cn.utmContent}`);
    lines.push(hr());
  }

  return lines.join("\n");
}
