import type { WizardInputs } from "@/types/wizard";

export interface FunnelTemplate {
  id: string;
  funnelType: "challenge" | "application";
  label: string;
  tagline: string;
  colour: string;         // Tailwind colour key
  emoji: string;
  prefill: Partial<WizardInputs>;
}

export const FUNNEL_TEMPLATES: FunnelTemplate[] = [
  // ── Challenge funnels ────────────────────────────────────────────────────────
  {
    id: "womens-weight-loss",
    funnelType: "challenge",
    label: "Women's Weight Loss Challenge",
    tagline: "Busy mums • lose weight without intense gym sessions",
    colour: "rose",
    emoji: "🔥",
    prefill: {
      funnelType: "challenge",
      duration: 30,
      price: "£37",
      ctaType: "booking",
      colourScheme: "rose-pink",
      toneOfVoice: "friendly",
      copywriterStyle: "halbert",
      mainGoal: "Lose weight and build sustainable habits without restrictive diets or gruelling gym sessions",
      biggestStruggle: "Previous attempts at weight loss failed because diets were too strict, exercise routines were unsustainable, or I didn't have proper accountability",
      objections: "I don't have time for meal prep or lengthy gym sessions; I've tried diets before and they didn't stick; I don't believe quick results are real",
      whatTheyTried: "Commercial diets (Weight Watchers, Slimming World); Home workout DVDs; gym memberships that went unused; calorie-counting apps that felt too rigid",
      trafficSources: ["facebook", "instagram", "local"],
      adBudgetRange: "£5–15/day",
      targetAudience: "Busy mums aged 30–50 who want to lose 1–2 stone, reclaim confidence, and have more energy for their families",
      demographicDetails: "Often work part-time or full-time; juggling kids, work, and household; time-poor but financially stable",
      inclusions: "Daily 20-minute workout videos; Weekly nutrition guide with meal ideas; Private Facebook group for support; Live Q&A calls twice a week; Progress tracking templates",
      bonuses: "Free before-and-after photo guide; Bonus 30-minute workout playlist; Post-challenge meal plan to keep results",
      namedMethod: "The 80/20 Method",
    },
  },
  {
    id: "mens-body-recomp",
    funnelType: "challenge",
    label: "Men's Strength & Fat Loss",
    tagline: "Desk-bound men • build muscle and shed fat without overcomplicating it",
    colour: "blue",
    emoji: "💪",
    prefill: {
      funnelType: "challenge",
      duration: 30,
      price: "£47",
      ctaType: "booking",
      colourScheme: "navy-orange",
      toneOfVoice: "bold",
      copywriterStyle: "hormozi",
      mainGoal: "Build visible muscle and lose fat simultaneously without living in the gym or eating like a robot",
      biggestStruggle: "Spent years at the gym with little to show; dieted hard but still look flabby; don't know if I'm training or eating right; lack the discipline to stick with a plan",
      objections: "I've been training for years with no results; building muscle and losing fat at the same time is impossible; I need to eat a huge amount to build muscle; I don't have time for meal prep",
      whatTheyTried: "Heavy barbell training without a nutrition plan; Crash diets that killed muscle; Expensive gym memberships; Instagram 'get shredded' programmes",
      trafficSources: ["facebook", "instagram"],
      adBudgetRange: "£8–20/day",
      targetAudience: "Men aged 35–55 with desk jobs who want visible muscle definition, more confidence, and better health without obsession",
      demographicDetails: "Desk workers; previously active in their 20s; high disposable income; frustrated with past results",
      inclusions: "3x weekly strength workouts (45 mins each); Meal plans and grocery lists; Weekly coaching videos; Private community with daily check-ins; Body metrics tracking",
      bonuses: "Home dumbbell workout alternative; Pre-workout nutrition timing guide; Supplement guide (non-BS recommendations)",
      namedMethod: "Compound Recomposition",
    },
  },
  {
    id: "nutrition-reset",
    funnelType: "challenge",
    label: "Nutrition Reset Challenge",
    tagline: "Anyone • understand food better and break unhealthy eating cycles",
    colour: "teal",
    emoji: "🥗",
    prefill: {
      funnelType: "challenge",
      duration: 21,
      price: "£22",
      ctaType: "booking",
      colourScheme: "teal-forest",
      toneOfVoice: "simple",
      copywriterStyle: "schwartz",
      mainGoal: "Learn the fundamentals of nutrition, reset eating habits, and feel energised again without restrictive rules",
      biggestStruggle: "Feel bloated and sluggish after eating; crave sugar and carbs constantly; don't understand nutrition; tried fad diets that left me hungry and miserable",
      objections: "I hate salads and 'healthy' food; nutrition is too complicated; I've tried eating well before and it didn't work; I'm too busy to meal plan",
      whatTheyTried: "Keto; Vegan diets; Intermittent fasting; Counting calories; Gym-only fitness with no nutrition changes",
      trafficSources: ["facebook", "instagram", "google"],
      adBudgetRange: "£3–8/day",
      targetAudience: "Mixed gender, aged 25–45, wanting to understand food, boost energy, and lose bloating without rigid rules",
      demographicDetails: "Often frustrated with conflicting nutrition advice; busy professionals; interested in simplicity over perfection",
      inclusions: "21 daily nutrition lessons (5 mins each); Real-food meal ideas and recipes; Shopping list templates; Energy and digestion tracking; Private Q&A group",
      bonuses: "Guide to eating out while staying on track; Restaurant menu decoder; Supplement breakdown (what actually works)",
      namedMethod: "Intuitive Nutrition Fundamentals",
    },
  },
  {
    id: "postpartum-comeback",
    funnelType: "challenge",
    label: "Postpartum Comeback Challenge",
    tagline: "New mums • reclaim your body and energy after birth",
    colour: "rose",
    emoji: "👶",
    prefill: {
      funnelType: "challenge",
      duration: 30,
      price: "£37",
      ctaType: "booking",
      colourScheme: "rose-pink",
      toneOfVoice: "friendly",
      copywriterStyle: "halbert",
      mainGoal: "Recover strength, rebuild confidence, and get your body back without rushing or ignoring postpartum safety",
      biggestStruggle: "Lost my body identity after pregnancy; scared to exercise again in case I hurt myself; no energy; isolated and touched-out from baby care",
      objections: "What if exercise causes problems with my healing?; I'm too tired to exercise; I don't recognise my body anymore; My partner doesn't understand what I'm going through",
      whatTheyTried: "Rushed back to pre-pregnancy routines and got injured; Avoided exercise entirely; Generic 'postpartum' programmes that didn't feel personal",
      trafficSources: ["facebook", "instagram"],
      adBudgetRange: "£5–12/day",
      targetAudience: "New mums aged 25–40, 6 months to 2 years postpartum, wanting safe recovery and body confidence",
      demographicDetails: "Range of delivery methods (vaginal, C-section); varying fitness backgrounds; often feeling isolated; desire community with others in same stage",
      inclusions: "Safe postpartum-specific workouts; Pelvic floor health guidance; Nutrition for recovery and energy; Private community of mums in same phase; Live support calls",
      bonuses: "Partner communication guide; Pelvic floor assessment video; Sleep optimisation tips for new parents",
      namedMethod: "The Postpartum Revival",
    },
  },

  // ── Application funnels ──────────────────────────────────────────────────────
  {
    id: "high-ticket-coaching",
    funnelType: "application",
    label: "High-Ticket Coaching Programme",
    tagline: "High-achievers • transformation through 1-on-1 or small-group coaching",
    colour: "purple",
    emoji: "🏆",
    prefill: {
      funnelType: "application",
      duration: 84,
      price: "£3,500",
      ctaType: "booking",
      colourScheme: "purple-lilac",
      toneOfVoice: "premium",
      copywriterStyle: "ogilvy",
      mainGoal: "Achieve [specific transformation] through personalised coaching, accountability, and a proven system designed for your situation",
      biggestStruggle: "I know what to do but can't stay consistent; I've invested in courses but don't follow through; I'm plateaued and need expert guidance to break through",
      objections: "I've spent money on coaching before with no results; Coaching won't work for my situation; I can figure this out on my own; How do I know you can deliver?",
      whatTheyTried: "Online courses and YouTube; DIY programmes; Other coaches (with mixed results); Trying solo without structure",
      trafficSources: ["facebook", "instagram", "organic"],
      adBudgetRange: "£10–30/day",
      targetAudience: "High-achievers aged 30–50 with disposable income, willing to invest in proven results, ready to commit to a structured programme",
      demographicDetails: "Often already successful in one area (business, career); willing to invest money and time; results-oriented; seeking private or small-group support",
      inclusions: "84-day structured programme in 3 phases; Weekly 1-on-1 coaching calls; Daily access via private portal; Accountability check-ins; Done-for-you templates and tools",
      bonuses: "90-day results guarantee; Private network of peers; Access to exclusive content library",
      namedMethod: "Elite Transformation System",
    },
  },
  {
    id: "body-transformation-90",
    funnelType: "application",
    label: "90-Day Body Transformation",
    tagline: "Men & women • serious results through 1:1 coaching",
    colour: "violet",
    emoji: "🔱",
    prefill: {
      funnelType: "application",
      duration: 90,
      price: "£3,497 – £4,997",
      ctaType: "booking",
      colourScheme: "navy-orange",
      toneOfVoice: "bold",
      copywriterStyle: "hormozi",
      mainGoal: "Help committed individuals achieve a complete body transformation — losing 2–3 stone and building the body they've always wanted — through personalised 1:1 coaching over 90 days",
      biggestStruggle: "Yo-yo dieting, starting over every few months, lack of accountability, generic programmes that don't fit their lifestyle or schedule",
      objections: "It's a big investment; I've tried coaching before; I don't know if I can commit; I've never seen results that actually last",
      whatTheyTried: "Multiple diets and programmes; Gym memberships; Group fitness classes; Online courses; Cheaper coaching options that didn't deliver",
      trafficSources: ["instagram", "facebook"],
      adBudgetRange: "£10–25/day",
      targetAudience: "High-achieving men and women aged 30–55 who have tried everything and are ready to invest seriously in a permanent transformation with a dedicated coach",
      demographicDetails: "Professionals with disposable income; have tried multiple approaches; results-oriented; frustrated with inconsistency",
      inclusions: "Fully personalised training programme; 1:1 nutrition coaching; Weekly video check-ins; 24/7 WhatsApp support; Mindset coaching; Progress tracking dashboard",
      bonuses: "Body composition analysis; 30-day post-programme maintenance plan; Alumni community access",
      investmentRange: "£3,497 single pay or 3 × £1,299",
      roiAnchor: "one new client pays for the entire investment",
      programPillars: "1. Personalised Training, 2. Precision Nutrition, 3. Mindset & Habits, 4. Accountability & Support, 5. Lifestyle Integration",
      idealClientProfile: "Motivated and coachable; willing to follow the plan; has tried other approaches; ready to invest in themselves; wants permanent change",
      notForWho: "Looking for a quick fix; not willing to follow guidance; unable to commit; expecting results without consistent effort",
      coachingCapacity: "Maximum 8 clients at any one time",
      namedMethod: "The Transformation Protocol",
    },
  },
  {
    id: "womens-hormone-reset",
    funnelType: "application",
    label: "Women's Hormone & Fat Loss Reset",
    tagline: "Women 35+ • fix metabolism and hormones for lasting results",
    colour: "purple",
    emoji: "✨",
    prefill: {
      funnelType: "application",
      duration: 84,
      price: "£2,497 – £3,297",
      ctaType: "booking",
      colourScheme: "purple-lilac",
      toneOfVoice: "premium",
      copywriterStyle: "schwartz",
      mainGoal: "Help women over 35 fix their metabolism, balance hormones, and lose 1.5–2 stone sustainably without restrictive dieting — through a science-backed 12-week coaching programme",
      biggestStruggle: "Weight that won't shift despite eating well, extreme fatigue, mood swings, being told everything is 'normal' by their GP",
      objections: "I don't know if this is the right time; I've spent a lot on health already; how is this different from what I've tried; I'm not sure hormones are the issue",
      whatTheyTried: "Standard calorie-deficit diets; High-intensity exercise (which made things worse); GP advice; Supplements; Other weight loss programmes",
      trafficSources: ["instagram", "facebook"],
      adBudgetRange: "£8–20/day",
      targetAudience: "Women over 35 who are doing everything right — eating healthy, exercising — but still gaining weight and feeling exhausted. Often suspect hormonal involvement.",
      demographicDetails: "Women 35–55, perimenopause or menopause, professional, health-conscious but frustrated with results that don't match the effort",
      inclusions: "Hormone-optimised nutrition strategy; Cycle-synced training plan; Weekly 1:1 coaching calls; Private coaching portal; Progress tracking and lab results interpretation",
      bonuses: "Hormone health guide; Stress & cortisol management protocol; Sleep optimisation programme",
      investmentRange: "£2,497 single pay or 2 × £1,297",
      roiAnchor: "equivalent to less than £30 per day for a permanent solution",
      programPillars: "1. Metabolic Reset, 2. Hormone Optimisation, 3. Sustainable Nutrition, 4. Strength & Movement, 5. Stress & Sleep",
      idealClientProfile: "Women 35+ who suspect hormonal involvement, have tried standard diets without success, ready for a science-backed personalised approach",
      notForWho: "Looking for a quick-fix crash diet; not willing to make lifestyle changes; not ready to invest in their health",
      coachingCapacity: "6 spots available per intake",
      namedMethod: "The Hormone Reset Method",
    },
  },
];
