import type { WizardInputs } from "@/types/wizard";

export interface FunnelTemplate {
  id: string;
  funnelType: "challenge" | "application";
  label: string;
  tagline: string;
  colour: string;         // Tailwind colour key
  emoji: string;
  prefill: Partial<WizardInputs>;
}

export const FUNNEL_TEMPLATES: FunnelTemplate[] = [
  // ── Challenge funnels ────────────────────────────────────────────────────────
  {
    id: "fat-loss-28",
    funnelType: "challenge",
    label: "28-Day Fat Loss",
    tagline: "Busy women • lose weight without starving",
    colour: "rose",
    emoji: "🔥",
    prefill: {
      funnelType:         "challenge",
      challengeName:      "28-Day Fat Loss Challenge",
      challengeType:      "Weight Loss",
      mainGoal:           "Help busy women drop 8–14 lbs in 28 days through simple daily workouts and a sustainable nutrition plan — without cutting out the foods they love",
      duration:           28,
      price:              "£47 or free with upsell",
      ctaType:            "signup",
      inclusions:         "Daily 20-minute home workouts, simple meal plan, accountability group, weekly check-in calls, progress tracker",
      targetAudience:     "Busy women aged 30–50 who have tried diets before, lost motivation, and want a structured short challenge to kickstart their results",
      audienceDemographic:"Women 30–50, mums, office workers, time-poor, moderate fitness level",
      biggestStruggle:    "Starting over every Monday, no time for long gym sessions, emotional eating, feeling overwhelmed by conflicting nutrition advice",
      objections:         "I've tried this before and it didn't work; I don't have time; I can't afford a gym; I'm too busy with the kids",
      toneOfVoice:        "friendly",
      colourScheme:       "rose-pink",
      trafficSources:     ["facebook", "instagram"],
      hasBeforeAfter:     true,
    },
  },
  {
    id: "muscle-build-30",
    funnelType: "challenge",
    label: "30-Day Muscle Build",
    tagline: "Men 25–45 • strength & definition",
    colour: "blue",
    emoji: "💪",
    prefill: {
      funnelType:         "challenge",
      challengeName:      "30-Day Muscle Build Challenge",
      challengeType:      "Strength & Muscle",
      mainGoal:           "Help men aged 25–45 build visible muscle, increase strength, and improve body composition in 30 days using progressive training and optimised nutrition",
      duration:           30,
      price:              "£47",
      ctaType:            "signup",
      inclusions:         "Progressive 4-day training split, high-protein meal guide, supplement protocol, weekly progress check-ins, private community",
      targetAudience:     "Men aged 25–45 who go to the gym but haven't seen the results they want — they train hard but lack a structured programme and nutrition strategy",
      audienceDemographic:"Men 25–45, intermediate gym-goers, working professionals, some experience but plateaued",
      biggestStruggle:    "Training hard with no visible results, inconsistent nutrition, not knowing what programme to follow, lack of accountability",
      objections:         "I already go to the gym and it's not working; I don't want to spend hours in the gym; I'm not sure about the nutrition side",
      toneOfVoice:        "bold",
      colourScheme:       "navy-orange",
      trafficSources:     ["instagram", "facebook"],
      hasBeforeAfter:     true,
    },
  },
  {
    id: "kickstart-21",
    funnelType: "challenge",
    label: "21-Day Kickstart",
    tagline: "Beginners • build the habit, feel the shift",
    colour: "teal",
    emoji: "⚡",
    prefill: {
      funnelType:         "challenge",
      challengeName:      "21-Day Kickstart Challenge",
      challengeType:      "Fitness Kickstart",
      mainGoal:           "Help complete beginners build a daily exercise habit, lose their first 5–8 lbs, and finally feel in control of their health in just 21 days",
      duration:           21,
      price:              "Free or £27",
      ctaType:            "signup",
      inclusions:         "Daily beginner-friendly workouts (15–20 mins), simple nutrition guide, accountability WhatsApp group, daily motivation emails",
      targetAudience:     "Complete beginners or returners who haven't exercised in years, feel embarrassed at the gym, and need an accessible starting point",
      audienceDemographic:"Adults 25–55, mixed gender, sedentary lifestyle, beginners",
      biggestStruggle:    "Never sticking to exercise, feeling judged at the gym, not knowing where to start, overwhelmed by complex programmes",
      objections:         "I've never been able to stick to exercise; I'm too unfit to start; I don't have gym equipment",
      toneOfVoice:        "motivational",
      colourScheme:       "teal-forest",
      trafficSources:     ["facebook", "instagram"],
      hasBeforeAfter:     false,
    },
  },

  // ── Application funnels ──────────────────────────────────────────────────────
  {
    id: "transformation-90",
    funnelType: "application",
    label: "90-Day Body Transformation",
    tagline: "High-ticket 1:1 • serious results",
    colour: "violet",
    emoji: "🏆",
    prefill: {
      funnelType:         "application",
      challengeName:      "90-Day Body Transformation Programme",
      challengeType:      "Premium Transformation",
      mainGoal:           "Help committed individuals achieve a complete body transformation — losing 2–3 stone and building the body they've always wanted — through personalised 1:1 coaching over 90 days",
      duration:           90,
      price:              "£3,497 – £4,997",
      ctaType:            "booking",
      inclusions:         "Fully personalised training programme, 1:1 nutrition coaching, weekly video check-ins, 24/7 WhatsApp support, mindset coaching, progress tracking",
      investmentRange:    "£3,497 single pay or 3 × £1,299",
      roiAnchor:          "one new client covers the full investment",
      targetAudience:     "High-achieving men and women aged 30–55 who have tried everything and are ready to invest seriously in a permanent transformation with a dedicated coach",
      audienceDemographic:"Adults 30–55, professional, disposable income, have tried multiple diets/programmes",
      biggestStruggle:    "Yo-yo dieting, starting over every few months, lack of accountability, generic programmes that don't fit their lifestyle",
      objections:         "It's a big investment; I've tried coaching before; I don't know if I can commit",
      toneOfVoice:        "premium",
      colourScheme:       "navy-orange",
      trafficSources:     ["instagram", "facebook"],
      hasBeforeAfter:     true,
      programPillars:     "1. Personalised Training, 2. Precision Nutrition, 3. Mindset & Habits, 4. Accountability & Support, 5. Lifestyle Integration",
      idealClientProfile: "Motivated, willing to follow the plan, has tried other approaches, ready to invest in themselves, wants permanent change not a quick fix",
      notForWho:          "Looking for a quick fix, not willing to follow guidance, unable to commit to the process, expecting results without effort",
      coachingCapacity:   "Maximum 8 clients at any one time",
    },
  },
  {
    id: "elite-12-week",
    funnelType: "application",
    label: "12-Week Elite Coaching",
    tagline: "Women • hormones • sustainable fat loss",
    colour: "purple",
    emoji: "✨",
    prefill: {
      funnelType:         "application",
      challengeName:      "12-Week Elite Body Reset",
      challengeType:      "Elite Coaching",
      mainGoal:           "Help women over 35 fix their metabolism, balance hormones, and lose 1.5–2 stone sustainably without restrictive dieting — through a science-backed 12-week coaching programme",
      duration:           84,
      price:              "£2,497 – £3,297",
      ctaType:            "booking",
      inclusions:         "Hormone-optimised nutrition strategy, cycle-synced training plan, weekly 1:1 coaching calls, lab results interpretation, private coaching portal",
      investmentRange:    "£2,497 single pay or 2 × £1,297",
      roiAnchor:          "equivalent to less than £30 per day for permanent results",
      targetAudience:     "Women over 35 who are doing everything right — eating healthy, exercising — but still gaining weight and feeling exhausted. Suspect hormonal issues.",
      audienceDemographic:"Women 35–55, perimenopause or menopause, professional, health-conscious but frustrated",
      biggestStruggle:    "Weight that won't shift despite eating well, extreme fatigue, mood swings, being told everything is 'normal' by their GP",
      objections:         "I don't know if this is the right time; I've spent a lot on health already; how is this different from what I've tried",
      toneOfVoice:        "premium",
      colourScheme:       "purple-lilac",
      trafficSources:     ["instagram", "facebook"],
      hasBeforeAfter:     true,
      programPillars:     "1. Metabolic Reset, 2. Hormone Optimisation, 3. Sustainable Nutrition, 4. Strength & Movement, 5. Stress & Sleep",
      idealClientProfile: "Women 35+ who suspect hormonal involvement, have tried standard diets without success, ready for a science-backed personalised approach",
      notForWho:          "Looking for a quick fix crash diet, not willing to make lifestyle changes, not ready to invest in their health",
      coachingCapacity:   "6 spots available per cohort",
    },
  },
];
